from kaitori_scraper.models.data import CollectionItem, ProductType

COLLECTION: list[CollectionItem] = [
    CollectionItem(
        id=1,
        name_jp="変幻の仮面 BOX",
        series="sv6",
        quantity=1,
        product_type=ProductType.BOX,
        search_keywords=["変幻の仮面", "変幻の仮面 BOX"],
    ),
    CollectionItem(
        id=2,
        name_jp="クリムゾンヘイズ BOX",
        series="sv5a",
        quantity=1,
        product_type=ProductType.BOX,
        search_keywords=["クリムゾンヘイズ", "クリムゾンヘイズ BOX"],
    ),
    CollectionItem(
        id=3,
        name_jp="サイバージャッジ BOX",
        series="sv5M",
        quantity=1,
        product_type=ProductType.BOX,
        search_keywords=["サイバージャッジ", "サイバージャッジ BOX"],
    ),
    CollectionItem(
        id=4,
        name_jp="ワイルドフォース BOX",
        series="sv5K",
        quantity=1,
        product_type=ProductType.BOX,
        search_keywords=["ワイルドフォース", "ワイルドフォース BOX"],
    ),
    CollectionItem(
        id=5,
        name_jp="シャイニートレジャーex BOX",
        series="sv4a",
        quantity=2,
        product_type=ProductType.BOX,
        search_keywords=["シャイニートレジャーex", "シャイニートレジャー"],
    ),
    CollectionItem(
        id=6,
        name_jp="未来の一閃 BOX",
        series="sv4M",
        quantity=1,
        product_type=ProductType.BOX,
        search_keywords=["未来の一閃", "未来の一閃 BOX"],
    ),
    CollectionItem(
        id=7,
        name_jp="黒炎の支配者 BOX",
        series="sv3",
        quantity=2,
        product_type=ProductType.BOX,
        search_keywords=["黒炎の支配者", "黒炎の支配者 BOX"],
    ),
    CollectionItem(
        id=8,
        name_jp="クレイバースト BOX",
        series="sv2D",
        quantity=2,
        product_type=ProductType.BOX,
        search_keywords=["クレイバースト", "クレイバースト BOX"],
    ),
    CollectionItem(
        id=9,
        name_jp="バイオレットex BOX",
        series="sv1V",
        quantity=1,
        product_type=ProductType.BOX,
        search_keywords=["バイオレットex", "バイオレットex BOX"],
    ),
    CollectionItem(
        id=10,
        name_jp="VSTARユニバース BOX",
        series="s12a",
        quantity=6,
        product_type=ProductType.BOX,
        search_keywords=["VSTARユニバース", "VSTAR ユニバース"],
    ),
    CollectionItem(
        id=11,
        name_jp="パラダイムトリガー BOX",
        series="s12",
        quantity=2,
        product_type=ProductType.BOX,
        search_keywords=["パラダイムトリガー", "パラダイムトリガー BOX"],
    ),
    CollectionItem(
        id=12,
        name_jp="タイムゲイザー BOX",
        series="s10D",
        quantity=1,
        product_type=ProductType.BOX,
        search_keywords=["タイムゲイザー", "タイムゲイザー BOX"],
    ),
    CollectionItem(
        id=13,
        name_jp="Pokémon GO スペシャルセット",
        series="s10b",
        quantity=1,
        product_type=ProductType.SET,
        search_keywords=["Pokémon GO スペシャル", "ポケモン GO スペシャル", "Pokemon GO スペシャル"],
    ),
    CollectionItem(
        id=14,
        name_jp="ポケモンカード151 BOX",
        series="sv2a",
        quantity=3,
        product_type=ProductType.BOX,
        search_keywords=["ポケモンカード151", "151 BOX", "ポケモン 151"],
    ),
    CollectionItem(
        id=15,
        name_jp="151 カードファイルセット",
        series="sv2a",
        quantity=2,
        product_type=ProductType.SET,
        search_keywords=["151 カードファイル", "カードファイルセット 151"],
    ),
    CollectionItem(
        id=16,
        name_jp="ポケモンカードゲーム Classic",
        series="CL",
        quantity=1,
        product_type=ProductType.SET,
        search_keywords=["ポケモン Classic", "カードゲーム Classic", "ポケモンカードゲーム Classic"],
    ),
    CollectionItem(
        id=17,
        name_jp="スノーハザード＆クレイバースト ジムセット",
        series="sv2",
        quantity=1,
        product_type=ProductType.SET,
        search_keywords=["ジムセット ナンジャモ", "スノーハザード クレイバースト ジムセット"],
    ),
    CollectionItem(
        id=18,
        name_jp="スターターセットex ピカチュウ",
        series="svC",
        quantity=1,
        product_type=ProductType.SET,
        search_keywords=["スターターセットex ピカチュウ", "スターター ピカチュウ"],
    ),
]


def get_collection_by_ids(ids: list[int] | None = None) -> list[CollectionItem]:
    if ids is None:
        return COLLECTION
    return [item for item in COLLECTION if item.id in ids]
